// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-bookings.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_bookings_default = defineTool({
  name: "list_bookings",
  title: "List bookings",
  description: "List upcoming or recent bookings for the signed-in user's business. Returns booking code, customer name/phone, service, staff, start/end time, status, and payment status.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).describe("Max rows to return (default 25).").optional(),
    status: z.enum(["confirmed", "pending", "cancelled", "completed", "no_show"]).describe("Filter by booking status.").optional(),
    from: z.string().describe("ISO date/time lower bound on start_time.").optional(),
    to: z.string().describe("ISO date/time upper bound on start_time.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status, from, to }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let q = sb.from("bookings").select(
      "booking_code, customer_name, customer_phone, customer_email, start_time, end_time, status, payment_status, party_size, notes, service_id, staff_id, business_id"
    ).order("start_time", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    if (from) q = q.gte("start_time", from);
    if (to) q = q.lte("start_time", to);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { bookings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-customers.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_customers_default = defineTool2({
  name: "list_customers",
  title: "List customers",
  description: "List customers for the signed-in user's business, most recently updated first. Useful for lookups, exports, and analytics.",
  inputSchema: {
    search: z2.string().describe("Case-insensitive substring match on customer name, phone, or email.").optional(),
    limit: z2.number().int().min(1).max(200).describe("Max rows (default 50).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    let q = sb.from("customers").select("id, name, phone, email, total_visits, first_visit_date, preferred_language, notes_preferences, business_id, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 50);
    if (search && search.trim()) {
      const s = `%${search.trim()}%`;
      q = q.or(`name.ilike.${s},phone.ilike.${s},email.ilike.${s}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { customers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-calls.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_calls_default = defineTool3({
  name: "list_calls",
  title: "List recent calls",
  description: "List recent AI receptionist call log entries for the signed-in user's business, including caller, duration, outcome, and short summary.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).describe("Max rows (default 25).").optional(),
    needs_review_only: z3.boolean().describe("If true, only return calls flagged for review.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, needs_review_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    let q = sb.from("calls_log").select(
      "id, business_id, caller_name, caller_phone, to_number, call_type, call_outcome, duration_ms, summary, tags, needs_review, created_at"
    ).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (needs_review_only) q = q.eq("needs_review", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { calls: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_services_default = defineTool4({
  name: "list_services",
  title: "List services",
  description: "List the services (menu of offerings) configured for the signed-in user's business, with price and duration.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    const { data, error } = await sb.from("services").select("id, name, description, category, price, duration_minutes, deposit_required, deposit_amount, business_id").order("category", { ascending: true }).order("name", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { services: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-business-info.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.86.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_business_info_default = defineTool5({
  name: "get_business_info",
  title: "Get business info",
  description: "Return the signed-in user's business profile: name, type, address, main phone, website, hours-related settings, and Aivia AI receptionist status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser5(ctx);
    const { data, error } = await sb.from("businesses").select(
      "id, business_name, business_type, address, main_phone, secondary_phone, website, about_description, assigned_aivia_number, aivia_active, twilio_phone_number, booking_slug, custom_booking_domain, plan_tier, status"
    ).eq("owner_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "No business found for this user." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { business: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zyqzypyncugihrawhppg";
var mcp_default = defineMcp({
  name: "aivia-mcp",
  title: "Aivia",
  version: "0.1.0",
  instructions: "Tools for a business owner using Aivia (AI phone receptionist for salons and restaurants). Read the caller's bookings, customers, recent calls, services, and business profile. All tools act as the signed-in Aivia user and respect per-business isolation.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_business_info_default, list_bookings_default, list_customers_default, list_calls_default, list_services_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
